const { BUG, DRAGON, ELECTRIC, FIGHTING, FIRE, FLYING, GHOST, GRASS, GROUND, ICE, NORMAL, POISON, PSYCHIC, ROCK, WATER } = require("./types");
const { PHYSICAL, SPECIAL } = require("./categories");

const moves = [
  { index: 1, name: "Pound", type: NORMAL, category: PHYSICAL, pp: 35, power: 40, accuracy: 1 },
  { index: 2, name: "Karate Chop", type: NORMAL, category: PHYSICAL, pp: 25, power: 50, accuracy: 1 },
  { index: 3, name: "Double Slap", type: NORMAL, category: PHYSICAL, pp: 10, power: 15, accuracy: 0.85 },
  { index: 4, name: "Comet Punch", type: NORMAL, category: PHYSICAL, pp: 15, power: 18, accuracy: 0.85 },
  { index: 5, name: "Mega Punch", type: NORMAL, category: PHYSICAL, pp: 20, power: 80, accuracy: 0.85 },
  { index: 6, name: "Pay Day", type: NORMAL, category: PHYSICAL, pp: 20, power: 40, accuracy: 1 },
  { index: 7, name: "Fire Punch", type: FIRE, category: PHYSICAL, pp: 15, power: 75, accuracy: 1 },
  { index: 8, name: "Ice Punch", type: ICE, category: PHYSICAL, pp: 15, power: 75, accuracy: 1 },
  { index: 9, name: "Thunder Punch", type: ELECTRIC, category: PHYSICAL, pp: 15, power: 75, accuracy: 1 },
  { index: 10, name: "Scratch", type: NORMAL, category: PHYSICAL, pp: 35, power: 40, accuracy: 1 },
  { index: 11, name: "Vice Grip", type: NORMAL, category: PHYSICAL, pp: 30, power: 55, accuracy: 1 },
  { index: 13, name: "Razor Wind", type: NORMAL, category: SPECIAL, pp: 10, power: 80, accuracy: 0.75 },
  { index: 15, name: "Cut", type: NORMAL, category: PHYSICAL, pp: 30, power: 50, accuracy: 0.95 },
  { index: 16, name: "Gust", type: NORMAL, category: SPECIAL, pp: 35, power: 40, accuracy: 1 },
  { index: 17, name: "Wing Attack", type: FLYING, category: PHYSICAL, pp: 35, power: 35, accuracy: 1 },
  { index: 19, name: "Fly", type: FLYING, category: PHYSICAL, pp: 15, power: 70, accuracy: 0.95 },
  { index: 20, name: "Bind", type: NORMAL, category: PHYSICAL, pp: 20, power: 15, accuracy: 0.75 },
  { index: 21, name: "Slam", type: NORMAL, category: PHYSICAL, pp: 20, power: 80, accuracy: 0.75 },
  { index: 22, name: "Vine Whip", type: GRASS, category: PHYSICAL, pp: 10, power: 35, accuracy: 1 },
  { index: 23, name: "Stomp", type: NORMAL, category: PHYSICAL, pp: 20, power: 65, accuracy: 1 },
  { index: 24, name: "Double Kick", type: FIGHTING, category: PHYSICAL, pp: 30, power: 30, accuracy: 1 },
  { index: 25, name: "Mega Kick", type: NORMAL, category: PHYSICAL, pp: 5, power: 120, accuracy: 0.75 },
  { index: 26, name: "Jump Kick", type: FIGHTING, category: PHYSICAL, pp: 25, power: 70, accuracy: 0.95 },
  { index: 27, name: "Rolling Kick", type: FIGHTING, category: PHYSICAL, pp: 15, power: 60, accuracy: 0.85 },
  { index: 29, name: "Headbutt", type: NORMAL, category: PHYSICAL, pp: 15, power: 70, accuracy: 1 },
  { index: 30, name: "Horn Attack", type: NORMAL, category: PHYSICAL, pp: 25, power: 65, accuracy: 1 },
  { index: 31, name: "Fury Attack", type: NORMAL, category: PHYSICAL, pp: 20, power: 15, accuracy: 0.85 },
  { index: 33, name: "Tackle", type: NORMAL, category: PHYSICAL, pp: 35, power: 35, accuracy: 0.95 },
  { index: 34, name: "Body Slam", type: NORMAL, category: PHYSICAL, pp: 15, power: 85, accuracy: 1 },
  { index: 35, name: "Wrap", type: NORMAL, category: PHYSICAL, pp: 20, power: 15, accuracy: 0.85 },
  { index: 36, name: "Take Down", type: NORMAL, category: PHYSICAL, pp: 20, power: 90, accuracy: 0.85 },
  { index: 37, name: "Thrash", type: NORMAL, category: PHYSICAL, pp: 20, power: 90, accuracy: 1 },
  { index: 38, name: "Double-Edge", type: NORMAL, category: PHYSICAL, pp: 15, power: 100, accuracy: 1 },
  { index: 40, name: "Poison Sting", type: POISON, category: PHYSICAL, pp: 35, power: 15, accuracy: 1 },
  { index: 41, name: "Twineedle", type: BUG, category: PHYSICAL, pp: 20, power: 25, accuracy: 1 },
  { index: 42, name: "Pin Missile", type: BUG, category: PHYSICAL, pp: 20, power: 14, accuracy: 0.85 },
  { index: 44, name: "Bite", type: NORMAL, category: PHYSICAL, pp: 25, power: 60, accuracy: 1 },
  { index: 49, name: "Sonic Boom", type: NORMAL, category: SPECIAL, pp: 20, damage: 20, accuracy: 0.9 },
  { index: 51, name: "Acid", type: POISON, category: SPECIAL, pp: 30, power: 40, accuracy: 1 },
  { index: 52, name: "Ember", type: FIRE, category: SPECIAL, pp: 25, power: 40, accuracy: 1 },
  { index: 53, name: "Flamethrower", type: FIRE, category: SPECIAL, pp: 15, power: 95, accuracy: 1 },
  { index: 55, name: "Water Gun", type: WATER, category: SPECIAL, pp: 25, power: 40, accuracy: 1 },
  { index: 56, name: "Hydro Pump", type: WATER, category: SPECIAL, pp: 5, power: 120, accuracy: 0.8 },
  { index: 57, name: "Surf", type: WATER, category: SPECIAL, pp: 15, power: 95, accuracy: 1 },
  { index: 58, name: "Ice Beam", type: ICE, category: SPECIAL, pp: 10, power: 95, accuracy: 1 },
  { index: 59, name: "Blizzard", type: ICE, category: SPECIAL, pp: 5, power: 120, accuracy: 0.895 },
  { index: 60, name: "Psybeam", type: PSYCHIC, category: SPECIAL, pp: 20, power: 65, accuracy: 1 },
  { index: 61, name: "Bubble Beam", type: WATER, category: SPECIAL, pp: 20, power: 65, accuracy: 1 },
  { index: 62, name: "Aurora Beam", type: ICE, category: SPECIAL, pp: 20, power: 65, accuracy: 1 },
  { index: 63, name: "Hyper Beam", type: NORMAL, category: SPECIAL, pp: 5, power: 150, accuracy: 0.9 },
  { index: 64, name: "Peck", type: FLYING, category: PHYSICAL, pp: 35, power: 35, accuracy: 1 },
  { index: 65, name: "Drill Peck", type: FLYING, category: PHYSICAL, pp: 20, power: 80, accuracy: 1 },
  { index: 66, name: "Submission", type: FIGHTING, category: PHYSICAL, pp: 25, power: 80, accuracy: 0.8 },
  { index: 67, name: "Low Kick", type: FIGHTING, category: PHYSICAL, pp: 20, power: 50, accuracy: 0.9 },
  { index: 70, name: "Strength", type: NORMAL, category: PHYSICAL, pp: 15, power: 80, accuracy: 1 },
  { index: 71, name: "Absorb", type: GRASS, category: SPECIAL, pp: 20, power: 20, accuracy: 1 },
  { index: 72, name: "Mega Drain", type: GRASS, category: SPECIAL, pp: 10, power: 40, accuracy: 1 },
  { index: 75, name: "Razor Leaf", type: GRASS, category: PHYSICAL, pp: 25, power: 55, accuracy: 0.95 },
  { index: 76, name: "Solar Beam", type: GRASS, category: SPECIAL, pp: 10, power: 120, accuracy: 1 },
  { index: 80, name: "Petal Dance", type: GRASS, category: SPECIAL, pp: 20, power: 70, accuracy: 1 },
  { index: 82, name: "Dragon Rage", type: DRAGON, category: SPECIAL, pp: 10, damage: 40, accuracy: 1 },
  { index: 83, name: "Fire Spin", type: FIRE, category: SPECIAL, pp: 15, power: 15, accuracy: 0.7 },
  { index: 84, name: "Thunder Shock", type: ELECTRIC, category: SPECIAL, pp: 30, power: 40, accuracy: 1 },
  { index: 85, name: "Thunderbolt", type: ELECTRIC, category: SPECIAL, pp: 15, power: 95, accuracy: 1 },
  { index: 87, name: "Thunder", type: ELECTRIC, category: SPECIAL, pp: 10, power: 120, accuracy: 0.7 },
  { index: 88, name: "Rock Throw", type: ROCK, category: PHYSICAL, pp: 15, power: 50, accuracy: 0.65 },
  { index: 89, name: "Earthquake", type: GROUND, category: PHYSICAL, pp: 10, power: 100, accuracy: 1 },
  { index: 91, name: "Dig", type: GROUND, category: PHYSICAL, pp: 10, power: 100, accuracy: 1 },
  { index: 93, name: "Confusion", type: PSYCHIC, category: SPECIAL, pp: 25, power: 50, accuracy: 1 },
  { index: 94, name: "Psychic", type: PSYCHIC, category: SPECIAL, pp: 10, power: 90, accuracy: 1 },
  { index: 98, name: "Quick Attack", type: NORMAL, category: PHYSICAL, pp: 30, power: 40, accuracy: 1, priority: 1 },
  { index: 99, name: "Rage", type: NORMAL, category: PHYSICAL, pp: 20, power: 20, accuracy: 1 },
  { index: 120, name: "Self-Destruct", type: NORMAL, category: PHYSICAL, pp: 5, power: 130, accuracy: 1 },
  { index: 121, name: "Egg Bomb", type: NORMAL, category: PHYSICAL, pp: 10, power: 100, accuracy: 0.75 },
  { index: 122, name: "Lick", type: GHOST, category: PHYSICAL, pp: 30, power: 20, accuracy: 1 },
  { index: 123, name: "Smog", type: POISON, category: SPECIAL, pp: 20, power: 20, accuracy: 0.7 },
  { index: 124, name: "Sludge", type: POISON, category: SPECIAL, pp: 20, power: 65, accuracy: 1 },
  { index: 125, name: "Bone Club", type: GROUND, category: PHYSICAL, pp: 20, power: 65, accuracy: 0.85 },
  { index: 126, name: "Fire Blast", type: FIRE, category: SPECIAL, pp: 5, power: 120, accuracy: 0.85 },
  { index: 127, name: "Waterfall", type: WATER, category: PHYSICAL, pp: 15, power: 80, accuracy: 1 },
  { index: 128, name: "Clamp", type: WATER, category: PHYSICAL, pp: 10, power: 35, accuracy: 0.75 },
  { index: 130, name: "Skull Bash", type: NORMAL, category: PHYSICAL, pp: 15, power: 100, accuracy: 1 },
  { index: 131, name: "Spike Cannon", type: NORMAL, category: PHYSICAL, pp: 15, power: 20, accuracy: 1 },
  { index: 132, name: "Constrict", type: NORMAL, category: PHYSICAL, pp: 35, power: 10, accuracy: 1 },
  { index: 136, name: "High Jump Kick", type: FIGHTING, category: PHYSICAL, pp: 20, power: 85, accuracy: 0.9 },
  { index: 138, name: "Dream Eater", type: PSYCHIC, category: SPECIAL, pp: 15, power: 100, accuracy: 1 },
  { index: 140, name: "Barrage", type: NORMAL, category: PHYSICAL, pp: 20, power: 15, accuracy: 0.85 },
  { index: 141, name: "Leech Life", type: BUG, category: PHYSICAL, pp: 15, power: 20, accuracy: 1 },
  { index: 143, name: "Sky Attack", type: FLYING, category: PHYSICAL, pp: 5, power: 140, accuracy: 0.9 },
  { index: 145, name: "Bubble", type: WATER, category: SPECIAL, pp: 30, power: 20, accuracy: 1 },
  { index: 146, name: "Dizzy Punch", type: NORMAL, category: PHYSICAL, pp: 10, power: 70, accuracy: 1 },
  { index: 152, name: "Crabhammer", type: WATER, category: PHYSICAL, pp: 10, power: 90, accuracy: 0.85 },
  { index: 153, name: "Explosion", type: NORMAL, category: PHYSICAL, pp: 5, power: 170, accuracy: 1 },
  { index: 154, name: "Fury Swipes", type: NORMAL, category: PHYSICAL, pp: 15, power: 18, accuracy: 0.8 },
  { index: 155, name: "Bonemerang", type: GROUND, category: PHYSICAL, pp: 10, power: 50, accuracy: 0.9 },
  { index: 157, name: "Rock Slide", type: ROCK, category: PHYSICAL, pp: 10, power: 75, accuracy: 0.9 },
  { index: 158, name: "Hyper Fang", type: NORMAL, category: PHYSICAL, pp: 15, power: 80, accuracy: 0.9 },
  { index: 161, name: "Tri Attack", type: NORMAL, category: SPECIAL, pp: 10, power: 80, accuracy: 1 },
  { index: 163, name: "Slash", type: NORMAL, category: PHYSICAL, pp: 20, power: 70, accuracy: 1 },
  { index: 165, name: "Struggle", type: NORMAL, category: PHYSICAL, pp: 10, power: 50, accuracy: 1 }
]

module.exports = moves;
